"""tabla de users

Revision ID: 4ab659b4eeae
Revises: 
Create Date: 2023-10-02 19:58:03.003611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ab659b4eeae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supply_chain_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supply_chain_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supply_chain_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supply_chain_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supply_chain_user_username'))

    op.drop_table('supply_chain_user')
    # ### end Alembic commands ###
